name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Remove any system agents on runner
        run: |
          rm -rf ~/.gradle || true
          rm -rf **/lib/agents || true
          echo "System agent folder removed"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Disable instrumentation globally
        run: |
          echo "org.gradle.instrumentation.agent.disabled=true" >> gradle.properties
          mkdir -p ~/.gradle
          echo "org.gradle.instrumentation.agent.disabled=true" >> ~/.gradle/gradle.properties
          echo "JAVA_TOOL_OPTIONS='-Dorg.gradle.instrumentation.agent.disabled=true'" >> $GITHUB_ENV

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew clean assembleDebug --no-configuration-cache --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
